spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_media_test
    username: postgres
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

social-media:
  app:
    secret: secret
    expiration: 86400000
